# Generated by Django 5.1.5 on 2025-01-24 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('MO', 'Mobiles'), ('DR', 'Drinks or Cool'), ('FR', 'Furniture'), ('TY', 'Toys'), ('BK', 'Bikes'), ('EL', 'Electronics'), ('SP', 'Sports'), ('FC', 'Fasion'), ('BT', 'Beauty')], max_length=2),
        ),
    ]
