# Generated by Django 5.1.5 on 2025-01-29 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_customer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Uttar Pradesh', 'Uttar Pradesh'), ('Chhattisgarh', 'Chhattisgarh'), ('Telangana', 'Telangana'), ('Gujarat', 'Gujarat'), ('Goa', 'Goa'), ('West Bengal', 'West Bengal'), ('Bihar', 'Bihar'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Haryana', 'Haryana'), ('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Tamil Nadu', 'Tamil Nadu'), ('Himachal Pradesh', 'Himachal Pradesh'), ('kerala', 'kerala'), ('Assam', 'Assam'), ('Chandigarh', 'Chandigarh'), ('Uttarakhand', 'Uttarakhand'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh')], max_length=100),
        ),
    ]
