# Generated by Django 5.1.5 on 2025-02-03 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_customer_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Goa', 'Goa'), ('Bihar', 'Bihar'), ('Tamil Nadu', 'Tamil Nadu'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Telangana', 'Telangana'), ('Haryana', 'Haryana'), ('Assam', 'Assam'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Uttarakhand', 'Uttarakhand'), ('West Bengal', 'West Bengal'), ('Chhattisgarh', 'Chhattisgarh'), ('kerala', 'kerala'), ('Gujarat', 'Gujarat'), ('Chandigarh', 'Chandigarh')], max_length=100),
        ),
    ]
