# Generated by Django 5.1.5 on 2025-02-05 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_customer_state_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('West Bengal', 'West Bengal'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Uttarakhand', 'Uttarakhand'), ('Assam', 'Assam'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Gujarat', 'Gujarat'), ('Bihar', 'Bihar'), ('kerala', 'kerala'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Telangana', 'Telangana'), ('Haryana', 'Haryana'), ('Chhattisgarh', 'Chhattisgarh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Chandigarh', 'Chandigarh'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Tamil Nadu', 'Tamil Nadu'), ('Goa', 'Goa')], max_length=100),
        ),
    ]
