# Generated by Django 5.1.5 on 2025-02-10 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_alter_customer_state_payment_orderplaced'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Andhra Pradesh', 'Andhra Pradesh'), ('Uttarakhand', 'Uttarakhand'), ('Bihar', 'Bihar'), ('Assam', 'Assam'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('Tamil Nadu', 'Tamil Nadu'), ('West Bengal', 'West Bengal'), ('Uttar Pradesh', 'Uttar Pradesh'), ('kerala', 'kerala'), ('Chhattisgarh', 'Chhattisgarh'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Gujarat', 'Gujarat'), ('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Goa', 'Goa'), ('Chandigarh', 'Chandigarh'), ('Haryana', 'Haryana'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Telangana', 'Telangana')], max_length=100),
        ),
    ]
