# Generated by Django 5.1.5 on 2025-02-10 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_alter_customer_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Chandigarh', 'Chandigarh'), ('Bihar', 'Bihar'), ('Uttarakhand', 'Uttarakhand'), ('Haryana', 'Haryana'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Jammu & Kashmir', 'Jammu & Kashmir'), ('West Bengal', 'West Bengal'), ('Chhattisgarh', 'Chhattisgarh'), ('Telangana', 'Telangana'), ('Assam', 'Assam'), ('Tamil Nadu', 'Tamil Nadu'), ('kerala', 'kerala'), ('Gujarat', 'Gujarat'), ('Goa', 'Goa'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands')], max_length=100),
        ),
    ]
