# Generated by Django 5.1.5 on 2025-02-10 09:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_alter_customer_state'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='state',
            field=models.CharField(choices=[('Jammu & Kashmir', 'Jammu & Kashmir'), ('Chhattisgarh', 'Chhattisgarh'), ('Uttarakhand', 'Uttarakhand'), ('Chandigarh', 'Chandigarh'), ('West Bengal', 'West Bengal'), ('Uttar Pradesh', 'Uttar Pradesh'), ('Tamil Nadu', 'Tamil Nadu'), ('Himachal Pradesh', 'Himachal Pradesh'), ('Bihar', 'Bihar'), ('kerala', 'kerala'), ('Andaman & Nicobar Islands', 'Andaman & Nicobar Islands'), ('Telangana', 'Telangana'), ('Goa', 'Goa'), ('Assam', 'Assam'), ('Haryana', 'Haryana'), ('Gujarat', 'Gujarat'), ('Arunachal Pradesh', 'Arunachal Pradesh'), ('Andhra Pradesh', 'Andhra Pradesh')], max_length=100),
        ),
        migrations.CreateModel(
            name='Wishlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
